In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("preprosssed_gridlock.csv")

In [3]:
df.head()

,event_type,latitude,longitude,address,event_cause,requires_road_closure,start_datetime,status,authenticated,modified_datetime,veh_type,veh_no,corridor,priority,created_date,client_id,created_by_id,last_modified_by_id,police_station,kgid
0,unplanned,13.040004,77.518099,"Mumbai Bengaluru Highway, Jalahalli Cross Junc...",vehicle_breakdown,False,2024-03-07 17:01:48.111+00,closed,yes,2024-03-07 19:35:47.871698+00,lcv,FKN00GL0000,Tumkur Road,High,2024-03-07 17:03:51.164032+00,1,FKUSR00000,FKUSR00001,Peenya,FKKG000000
1,unplanned,12.921876,77.645158,"19th Main Road, Heavie Halcyon, Agara, HSR Lay...",vehicle_breakdown,False,2024-01-30 04:07:24.173+00,resolved,yes,2024-01-30 04:17:46.828979+00,heavy_vehicle,FKN00GL0001,ORR East 1,High,2024-01-30 04:08:22.954979+00,1,FKUSR00002,FKUSR00001,HSR Layout,FKKG000001
2,unplanned,12.955622,77.585708,"Lalbagh Main Road, Dr Sri Shantaveera Swami Ci...",others,False,2023-11-11 06:18:03.343+00,closed,yes,2024-01-30 04:56:03.282003+00,others,FKKG000001,Non-corridor,Low,2023-11-11 06:20:00.989398+00,1,FKUSR00003,FKUSR00001,Wilson Garden,FKKG000002
3,unplanned,13.006147,77.579435,"Sankey Road, Bashyam Circle, Sadashiva Nagar, ...",tree_fall,True,2024-03-07 17:56:55.061+00,closed,yes,2024-03-14 07:42:05.55005+00,others,FKKG000002,Non-corridor,Low,2024-03-07 17:58:56.696892+00,1,FKUSR00004,FKUSR00001,Sadashivanagar,FKKG000003
4,unplanned,12.953980,77.585233,"Lalbagh Fort Road, Lalbagh Main Gate Junction,...",vehicle_breakdown,False,2024-01-30 04:56:32.348+00,closed,yes,2024-01-30 05:35:17.33908+00,private_bus,FKN00GL0002,Non-corridor,Low,2024-01-30 04:58:55.937662+00,1,FKUSR00003,FKUSR00001,Wilson Garden,FKKG000002

In [5]:
df.columns

Index(['event_type', 'latitude', 'longitude', 'address', 'event_cause',
       'requires_road_closure', 'start_datetime', 'status', 'authenticated',
       'modified_datetime', 'veh_type', 'veh_no', 'corridor', 'priority',
       'created_date', 'client_id', 'created_by_id', 'last_modified_by_id',
       'police_station', 'kgid'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8166 entries, 0 to 8165
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   event_type             8166 non-null   str
 1   latitude               8166 non-null   float64
 2   longitude              8166 non-null   float64
 3   address                8166 non-null   str
 4   event_cause            8166 non-null   str
 5   requires_road_closure  8166 non-null   bool
 6   start_datetime         8166 non-null   str
 7   status                 8166 non-null   str
 8   authenticated          8166 non-null   str
 9   modified_datetime      8166 non-null   str
 10  veh_type               8166 non-null   str
 11  veh_no                 8166 non-null   str
 12  corridor               8166 non-null   str
 13  priority               8166 non-null   str
 14  created_date           8166 non-null   str
 15  client_id              8166 non-null   int64
 16  created_by_id          8166 non-null   str
 17  last_modified_by_id    8166 non-null   str
 18  police_station         8166 non-null   str
 19  kgid                   8166 non-null   str
dtypes: bool(1), float64(2), int64(1), str(16)
memory usage: 1.2 MB

In [7]:
df.isnull().sum()

event_type               0
latitude                 0
longitude                0
address                  0
event_cause              0
requires_road_closure    0
start_datetime           0
status                   0
authenticated            0
modified_datetime        0
veh_type                 0
veh_no                   0
corridor                 0
priority                 0
created_date             0
client_id                0
created_by_id            0
last_modified_by_id      0
police_station           0
kgid                     0
dtype: int64

In [8]:
drop_cols=["address",
    "veh_no",
    "client_id",
    "created_by_id",
    "last_modified_by_id",
    "kgid",
    "created_date",
    "modified_datetime",
    "authenticated",
    "status"
          ]
df=df.drop(columns=drop_cols)

In [9]:
df.head()

,event_type,latitude,longitude,event_cause,requires_road_closure,start_datetime,veh_type,corridor,priority,police_station
0,unplanned,13.040004,77.518099,vehicle_breakdown,False,2024-03-07 17:01:48.111+00,lcv,Tumkur Road,High,Peenya
1,unplanned,12.921876,77.645158,vehicle_breakdown,False,2024-01-30 04:07:24.173+00,heavy_vehicle,ORR East 1,High,HSR Layout
2,unplanned,12.955622,77.585708,others,False,2023-11-11 06:18:03.343+00,others,Non-corridor,Low,Wilson Garden
3,unplanned,13.006147,77.579435,tree_fall,True,2024-03-07 17:56:55.061+00,others,Non-corridor,Low,Sadashivanagar
4,unplanned,12.953980,77.585233,vehicle_breakdown,False,2024-01-30 04:56:32.348+00,private_bus,Non-corridor,Low,Wilson Garden

In [10]:
df["start_datetime"] = pd.to_datetime(df["start_datetime"])

ValueError: time data "2024-02-12 02:05:46+00" doesn't match format "%Y-%m-%d %H:%M:%S.%f%z". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [11]:
df["start_datetime"] = pd.to_datetime(df["start_datetime"])
df["hour"] = df["start_datetime"].dt.hour
df["day_of_week"] = df["start_datetime"].dt.day_name()
df["month"] = df["start_datetime"].dt.month

ValueError: time data "2024-02-12 02:05:46+00" doesn't match format "%Y-%m-%d %H:%M:%S.%f%z". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [12]:
df["start_datetime"].head(10)

0       2024-03-07 17:01:48.111+00
1       2024-01-30 04:07:24.173+00
2       2023-11-11 06:18:03.343+00
3       2024-03-07 17:56:55.061+00
4       2024-01-30 04:56:32.348+00
5    2023-11-28 03:07:27.292421+00
6       2024-01-30 07:26:26.739+00
7       2024-01-30 06:05:59.339+00
8           2024-02-12 02:05:46+00
9       2024-01-30 05:25:50.078+00
Name: start_datetime, dtype: str

In [13]:
df["start_datetime"] = pd.to_datetime(
    df["start_datetime"],
    format="mixed",
    utc=True
)

In [14]:
df["start_datetime"].head()

0   2024-03-07 17:01:48.111000+00:00
1   2024-01-30 04:07:24.173000+00:00
2   2023-11-11 06:18:03.343000+00:00
3   2024-03-07 17:56:55.061000+00:00
4   2024-01-30 04:56:32.348000+00:00
Name: start_datetime, dtype: datetime64[us, UTC]

In [15]:
df["hour"] = df["start_datetime"].dt.hour

df["day_of_week"] = df["start_datetime"].dt.day_name()

df["month"] = df["start_datetime"].dt.month

In [16]:
df[["start_datetime", "hour", "day_of_week", "month"]].head()

                    start_datetime  hour day_of_week  month
0 2024-03-07 17:01:48.111000+00:00    17    Thursday      3
1 2024-01-30 04:07:24.173000+00:00     4     Tuesday      1
2 2023-11-11 06:18:03.343000+00:00     6    Saturday     11
3 2024-03-07 17:56:55.061000+00:00    17    Thursday      3
4 2024-01-30 04:56:32.348000+00:00     4     Tuesday      1

In [17]:
df.shape

(8166, 13)

In [18]:
df["priority"].value_counts()

priority
High    5027
Low     3139
Name: count, dtype: int64

In [19]:
df.columns

Index(['event_type', 'latitude', 'longitude', 'event_cause',
       'requires_road_closure', 'start_datetime', 'veh_type', 'corridor',
       'priority', 'police_station', 'hour', 'day_of_week', 'month'],
      dtype='str')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8166 entries, 0 to 8165
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   event_type             8166 non-null   str
 1   latitude               8166 non-null   float64
 2   longitude              8166 non-null   float64
 3   event_cause            8166 non-null   str
 4   requires_road_closure  8166 non-null   bool
 5   start_datetime         8166 non-null   datetime64[us, UTC]
 6   veh_type               8166 non-null   str
 7   corridor               8166 non-null   str
 8   priority               8166 non-null   str
 9   police_station         8166 non-null   str
 10  hour                   8166 non-null   int32
 11  day_of_week            8166 non-null   str
 12  month                  8166 non-null   int32
dtypes: bool(1), datetime64[us, UTC](1), float64(2), int32(2), str(7)
memory usage: 709.9 KB

In [21]:
df = df.drop(columns=["start_datetime"])

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8166 entries, 0 to 8165
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   event_type             8166 non-null   str
 1   latitude               8166 non-null   float64
 2   longitude              8166 non-null   float64
 3   event_cause            8166 non-null   str
 4   requires_road_closure  8166 non-null   bool
 5   veh_type               8166 non-null   str
 6   corridor               8166 non-null   str
 7   priority               8166 non-null   str
 8   police_station         8166 non-null   str
 9   hour                   8166 non-null   int32
 10  day_of_week            8166 non-null   str
 11  month                  8166 non-null   int32
dtypes: bool(1), float64(2), int32(2), str(7)
memory usage: 646.1 KB

In [23]:
df["requires_road_closure"] = df["requires_road_closure"].astype(int)

In [24]:
df["requires_road_closure"].head()

0    0
1    0
2    0
3    1
4    0
Name: requires_road_closure, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
encoders = {}

In [27]:
categorical_cols = [
    "event_type",
    "event_cause",
    "veh_type",
    "corridor",
    "police_station",
    "day_of_week"
]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

In [28]:
df["priority"] = df["priority"].map({
    "Low": 0,
    "High": 1
})

In [29]:
df["priority"].value_counts()

priority
1    5027
0    3139
Name: count, dtype: int64

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8166 entries, 0 to 8165
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   event_type             8166 non-null   int64
 1   latitude               8166 non-null   float64
 2   longitude              8166 non-null   float64
 3   event_cause            8166 non-null   int64
 4   requires_road_closure  8166 non-null   int64
 5   veh_type               8166 non-null   int64
 6   corridor               8166 non-null   int64
 7   priority               8166 non-null   int64
 8   police_station         8166 non-null   int64
 9   hour                   8166 non-null   int32
 10  day_of_week            8166 non-null   int64
 11  month                  8166 non-null   int32
dtypes: float64(2), int32(2), int64(8)
memory usage: 701.9 KB

In [31]:
df.head()

,event_type,latitude,longitude,event_cause,requires_road_closure,veh_type,corridor,priority,police_station,hour,day_of_week,month
0,1,13.040004,77.518099,14,0,4,19,1,39,17,4,3
1,1,12.921876,77.645158,14,0,2,12,1,15,4,5,1
2,1,12.955622,77.585708,6,0,5,11,0,51,6,2,11
3,1,13.006147,77.579435,13,1,5,11,0,43,17,4,3
4,1,12.953980,77.585233,14,0,6,11,0,51,4,5,1

In [32]:
df.to_csv(
    "preprocessed_data.csv",
    index=False
)